### ISSUE TITLE
Getting error on startup "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by iCarl** [ilcato/homebridge-mqttswitch#15]
```
/usr/lib/node_modules/homebridge-mqttswitch/node_modules/mqtt/lib/validations.js:42
  for (var i = 0; i < topics.length; i++) {
                            ^

TypeError: Cannot read property 'length' of undefined
    at Object.validateTopics (/usr/lib/node_modules/homebridge-mqttswitch/node_modules/mqtt/lib/validations.js:42:29)
    at MqttClient.subscribe (/usr/lib/node_modules/homebridge-mqttswitch/node_modules/mqtt/lib/client.js:417:30)
    at new MqttSwitchAccessory (/usr/lib/node_modules/homebridge-mqttswitch/index.js:89:17)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:265:29)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

Just installed this plugin.
My config looks like this:

```
"accessories": [
    {
      "accessory": "mqttswitch",
      "name": "Sonoff1",
      "url": "mqtt://10.0.1.5",
      "username": "",
      "password": "",
      "caption": "Sonoff1",
      "topics": {
        "statusSet": "Sonoff1"
      },
      "onValue": "on",
      "offValue": "off"
    },
    {
      "accessory": "mqttswitch",
      "name": "sonoff2",
      "url": "mqtt://10.0.1.5",
      "username": "",
      "password": "",
      "caption": "sonoff2",
      "topics": {
        "statusSet": "sonoff2"
      },
      "onValue": "on",
      "offValue": "off"
    },
    {
      "accessory": "mqttswitch",
      "name": "sonoff3",
      "url": "mqtt://10.0.1.5",
      "username": "",
      "password": "",
      "caption": "sonoff3",
      "topics": {
        "statusSet": "sonoff3"
      },
      "onValue": 1,
      "offValue": 0
    }
  ]
}
```

**Comment by iCarl** [comment]
@ilcato Can you help me?

**Comment by ilcato** [comment]
which version of node.js do you have?

**Comment by iCarl** [comment]
v6.9.5

**Comment by ilcato** [comment]
In the config.json you didn't specify the statusGet topics.

**Comment by desq42** [comment]
(I´m using "mqtt-sprinkler" (which was forked from your branch…) 
I would ask the author, but he has closed "issues"…)

…same issue here. My config;
```
        {
            "accessory": "mqtt-sprinkler",
            "name": "BetaBambus",
            "url": "mqtt://10.0.1.3",
            "username": "…",
            "password": "…",
            "topics": {
                "statusGet": "stat/sonoff4ch/POWER1",
                "statusSet": "cmnd/sonoff4ch/power1"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "integerValue": "false"
        },
```

> Error-Log;
> [37m[4/18/2019, 10:02:47 AM][39m [1m[31mTypeError: Cannot read property 'length' of undefined
>     at Object.validateTopics (/homebridge/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/validations.js:42:30)
>     at MqttClient.subscribe (/homebridge/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:417:30)
>     at MqttClient.MQTTClient.mqtt.on (/homebridge/node_modules/homebridge-mqtt-sprinkler/lib/MQTTClient.js:28:17)
>     at MqttClient.emit (events.js:194:15)
>     at MqttClient._handleConnack (/homebridge/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:732:10)
>     at MqttClient._handlePacket (/homebridge/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:296:12)
>     at process (/homebridge/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:238:12)
>     at Writable.writable._write (/homebridge/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:248:5)
>     at doWrite (/homebridge/node_modules/homebridge-mqtt-sprinkler/node_modules/readable-stream/lib/_stream_writable.js:237:10)
>     at writeOrBuffer (/homebridge/node_modules/homebridge-mqtt-sprinkler/node_modules/readable-stream/lib/_stream_writable.js:227:5)[39m[22m

**Comment by nixmeer** [comment]
@desq42 I get the same error using the same fork as you.
```
TypeError: Cannot read property 'length' of undefined
    at Object.validateTopics (/usr/lib/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/validations.js:42:30)
    at MqttClient.subscribe (/usr/lib/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:417:30)
    at MqttClient.MQTTClient.mqtt.on (/usr/lib/node_modules/homebridge-mqtt-sprinkler/lib/MQTTClient.js:28:17)
    at MqttClient.emit (events.js:164:20)
    at MqttClient._handleConnack (/usr/lib/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:732:10)
    at MqttClient._handlePacket (/usr/lib/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:296:12)
    at process (/usr/lib/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:238:12)
    at Writable.writable._write (/usr/lib/node_modules/homebridge-mqtt-sprinkler/node_modules/mqtt/lib/client.js:248:5)
    at doWrite (/usr/lib/node_modules/homebridge-mqtt-sprinkler/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/lib/node_modules/homebridge-mqtt-sprinkler/node_modules/readable-stream/lib/_stream_writable.js:227:5)
```

I tried adding all optional settings but it didn't help. 

``` 
{
                "accessory": "mqtt-sprinkler",
                "name": "TESTNAME",
                "url": "mqtt://192.168.178.76",
                "topics": {
                        "statusGet": "TESTGET",
                        "statusSet": "TESTSET"
                },
                "onValue": "on",
                "offValue": "off",
                "serialNumberMAC"       : "12:32:34:bf:ad",
                "caption"       : "Tomaten",
                "username"      : "123",
                "password"      : "1234",
                "integerValue"  : "true",
                "statusCmd"     : "statusCMD",
                "qos"           : "0"
        }
```

Any help appreciated!
